DEFAULT_REST_BASE        = 'https://pawoo.net'
DEFAULT_REST_API_POSTFIX = '/api/v1/'
DEFAULT_REST_ROOT        = DEFAULT_REST_BASE + DEFAULT_REST_API_POSTFIX

DEFAULT_OAUTH_APPS_ENDPOINT = '{0}apps'.format( DEFAULT_REST_ROOT )